---
- name: Télécharger WordPress
  get_url:
    url: https://wordpress.org/wordpress-6.6.2.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraire WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Configurer les permissions sur /var/www/html
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes

- name: Configurer le fichier wp-config.php
  copy:
    src: /var/www/html/wp-config-sample.php
    dest: /var/www/html/wp-config.php
    remote_src: yes

- name: Modifier wp-config.php avec les informations de la base de données
  lineinfile:
    path: /var/www/html/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: 'database_name_here', line: 'define("DB_NAME", "{{ dbw_name }}");' }
    - { regexp: 'username_here', line: 'define("DB_USER", "{{ dbw_user }}");' }
    - { regexp: 'password_here', line: 'define("DB_PASSWORD", "{{ dbw_password }}");' }


- name: Supprimer le fichier index.html par défaut
  file:
    path: /var/www/html/index.html
    state: absent

- name: Générer le fichier wordpress.conf pour Apache
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf

- name: Activer le site WordPress dans Apache
  command: a2ensite wordpress.conf
