---
- name: Installer et configurer WordPress
  hosts: wordpress
  become: true

  vars:
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  tasks:

    - name: Mise à jour de la liste des paquets
      apt:
        update_cache: yes

    - name: Installer Apache
      apt:
        name: apache2
        state: present

    - name: Démarrer et activer Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Installer les dépendances pour PHP
      apt:
        name: software-properties-common
        state: present

    - name: Ajouter le dépôt PHP PPA si nécessaire
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Installer PHP 8.3 et les modules nécessaires
      apt:
        name:
          - php8.3
          - libapache2-mod-php8.3
          - php8.3-mysql
        state: present

    - name: Pré-configurer MySQL root password
      debconf:
        name: mysql-community-server
        question: mysql-community-server/root-pass
        value: root
        vtype: password

    - name: Répéter la configuration de MySQL root password
      debconf:
        name: mysql-community-server
        question: mysql-community-server/re-root-pass
        value: root
        vtype: password

    - name: Installer MySQL
      apt:
        name: mysql-server
        state: present

    - name: Créer la base de données WordPress
      mysql_db:
        name: wordpress
        state: present
        login_user: root
        login_password: root

    - name: Créer un utilisateur WordPress
      mysql_user:
        name: wordpress
        password: password
        priv: 'wordpress.*:ALL'
        state: present
        login_user: root
        login_password: root

    - name: Télécharger WordPress
      get_url:
        url: https://wordpress.org/wordpress-6.6.2.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extraire WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: Configurer les permissions sur /var/www/html
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes

    - name: Configurer le fichier wp-config.php
      copy:
        src: /var/www/html/wp-config-sample.php
        dest: /var/www/html/wp-config.php

    - name: Modifier wp-config.php avec les informations de la base de données
      lineinfile:
        path: /var/www/html/wp-config.php
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: 'database_name_here', line: 'define("DB_NAME", "wordpress");' }
        - { regexp: 'username_here', line: 'define("DB_USER", "wordpress");' }
        - { regexp: 'password_here', line: 'define("DB_PASSWORD", "password");' }

    - name: Supprimer le fichier index.html par défaut
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Générer le fichier wordpress.conf pour Apache
      copy:
        dest: /etc/apache2/sites-available/wordpress.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/html
              ServerName localhost

              <Directory /var/www/html>
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Activer le site WordPress dans Apache
      command: a2ensite wordpress.conf

    - name: Activer le module rewrite d'Apache
      command: a2enmod rewrite

    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted

  handlers:
    - name: Redémarrer Apache après modification
      service:
        name: apache2
        state: restarted